[2025-01-22T23:07:11.391+0000] {processor.py:161} INFO - Started process (PID=17303) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:07:11.392+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:07:11.395+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:07:11.395+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:07:11.401+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:07:11.398+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:07:11.402+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:07:11.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.047 seconds
[2025-01-22T23:07:41.755+0000] {processor.py:161} INFO - Started process (PID=17368) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:07:41.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:07:41.775+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:07:41.774+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:07:41.780+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:07:41.779+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:07:41.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:07:41.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.065 seconds
[2025-01-22T23:08:11.952+0000] {processor.py:161} INFO - Started process (PID=17434) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:08:11.957+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:08:11.960+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:08:11.960+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:08:11.964+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:08:11.963+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:08:11.965+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:08:11.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.058 seconds
[2025-01-22T23:08:42.706+0000] {processor.py:161} INFO - Started process (PID=17500) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:08:42.706+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:08:42.709+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:08:42.708+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:08:42.712+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:08:42.711+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:08:42.713+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:08:42.742+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.040 seconds
[2025-01-22T23:09:12.811+0000] {processor.py:161} INFO - Started process (PID=17565) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:09:12.813+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:09:12.816+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:09:12.815+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:09:12.820+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:09:12.819+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:09:12.821+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:09:12.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.069 seconds
[2025-01-22T23:09:42.983+0000] {processor.py:161} INFO - Started process (PID=17631) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:09:42.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:09:42.987+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:09:42.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:09:42.992+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:09:42.991+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:09:42.993+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:09:43.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.049 seconds
[2025-01-22T23:10:13.186+0000] {processor.py:161} INFO - Started process (PID=17697) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:10:13.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:10:13.191+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:10:13.190+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:10:13.195+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:10:13.194+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:10:13.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:10:13.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.045 seconds
[2025-01-22T23:10:43.532+0000] {processor.py:161} INFO - Started process (PID=17763) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:10:43.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:10:43.535+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:10:43.535+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:10:43.539+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:10:43.538+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:10:43.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:10:43.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.043 seconds
[2025-01-22T23:11:13.763+0000] {processor.py:161} INFO - Started process (PID=17829) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:11:13.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:11:13.771+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:11:13.770+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:11:13.775+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:11:13.774+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:11:13.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:11:13.816+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.057 seconds
[2025-01-22T23:11:44.118+0000] {processor.py:161} INFO - Started process (PID=17900) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:11:44.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:11:44.121+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:11:44.121+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:11:44.125+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:11:44.124+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:11:44.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:11:44.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.062 seconds
[2025-01-22T23:12:14.457+0000] {processor.py:161} INFO - Started process (PID=17966) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:12:14.460+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:12:14.463+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:12:14.462+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:12:14.467+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:12:14.465+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:12:14.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:12:14.550+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.103 seconds
[2025-01-22T23:12:45.466+0000] {processor.py:161} INFO - Started process (PID=18031) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:12:45.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:12:45.471+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:12:45.470+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:12:45.480+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:12:45.479+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:12:45.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:12:45.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.078 seconds
[2025-01-22T23:13:16.124+0000] {processor.py:161} INFO - Started process (PID=18096) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:13:16.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:13:16.132+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:13:16.132+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:13:16.136+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:13:16.135+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:13:16.137+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:13:16.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.075 seconds
[2025-01-22T23:13:46.499+0000] {processor.py:161} INFO - Started process (PID=18162) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:13:46.501+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:13:46.503+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:13:46.503+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:13:46.508+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:13:46.507+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:13:46.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:13:46.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.078 seconds
[2025-01-22T23:14:16.710+0000] {processor.py:161} INFO - Started process (PID=18228) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:14:16.711+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:14:16.715+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:14:16.714+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:14:16.719+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:14:16.718+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:14:16.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:14:16.750+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.045 seconds
[2025-01-22T23:14:46.800+0000] {processor.py:161} INFO - Started process (PID=18285) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:14:46.801+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:14:46.803+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:14:46.802+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:14:46.806+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:14:46.805+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:14:46.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:14:46.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.036 seconds
[2025-01-22T23:15:17.287+0000] {processor.py:161} INFO - Started process (PID=18351) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:15:17.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:15:17.293+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:15:17.292+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:15:17.297+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:15:17.296+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:15:17.298+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:15:17.324+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.042 seconds
[2025-01-22T23:15:47.471+0000] {processor.py:161} INFO - Started process (PID=18413) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:15:47.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:15:47.476+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:15:47.475+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:15:47.488+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:15:47.480+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:15:47.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:15:47.582+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.117 seconds
[2025-01-22T23:16:18.354+0000] {processor.py:161} INFO - Started process (PID=18479) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:16:18.356+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:16:18.358+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:16:18.358+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:16:18.363+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:16:18.361+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:16:18.366+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:16:18.398+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.064 seconds
[2025-01-22T23:16:49.094+0000] {processor.py:161} INFO - Started process (PID=18545) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:16:49.096+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:16:49.099+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:16:49.098+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:16:49.103+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:16:49.102+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:16:49.104+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:16:49.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.048 seconds
[2025-01-22T23:17:19.249+0000] {processor.py:161} INFO - Started process (PID=18611) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:17:19.251+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:17:19.254+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:17:19.254+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:17:19.258+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:17:19.257+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:17:19.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:17:19.301+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.057 seconds
[2025-01-22T23:17:49.907+0000] {processor.py:161} INFO - Started process (PID=18679) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:17:49.908+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:17:49.911+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:17:49.911+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:17:49.922+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:17:49.914+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 46
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:17:49.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:17:49.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.067 seconds
[2025-01-22T23:18:09.999+0000] {processor.py:161} INFO - Started process (PID=18733) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:18:10.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:18:10.009+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:18:10.008+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:18:10.018+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:18:10.017+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 22
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:18:10.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:18:10.066+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.072 seconds
[2025-01-22T23:18:40.633+0000] {processor.py:161} INFO - Started process (PID=18799) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:18:40.634+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:18:40.637+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:18:40.636+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:18:40.649+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:18:40.647+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 22
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:18:40.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:18:40.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.100 seconds
[2025-01-22T23:19:11.201+0000] {processor.py:161} INFO - Started process (PID=18862) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:19:11.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:19:11.205+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:19:11.205+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:19:11.222+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:19:11.220+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 22
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:19:11.223+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:19:11.283+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.086 seconds
[2025-01-22T23:19:18.461+0000] {processor.py:161} INFO - Started process (PID=18873) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:19:18.462+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:19:18.464+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:19:18.464+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:19:18.471+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:19:18.469+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 22
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:19:18.471+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:19:18.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.116 seconds
[2025-01-22T23:19:49.493+0000] {processor.py:161} INFO - Started process (PID=18938) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:19:49.495+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:19:49.498+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:19:49.497+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:19:49.503+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:19:49.501+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 22
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:19:49.504+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:19:49.533+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.045 seconds
[2025-01-22T23:20:19.718+0000] {processor.py:161} INFO - Started process (PID=19000) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:20:19.719+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:20:19.722+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:20:19.721+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:20:19.725+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:20:19.724+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 22
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:20:19.726+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:20:19.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.042 seconds
[2025-01-22T23:20:49.912+0000] {processor.py:161} INFO - Started process (PID=19067) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:20:49.913+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:20:49.916+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:20:49.915+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:20:49.919+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:20:49.918+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 22
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:20:49.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:20:49.952+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.045 seconds
[2025-01-22T23:21:20.068+0000] {processor.py:161} INFO - Started process (PID=19133) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:21:20.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:21:20.082+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:21:20.082+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:21:20.087+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:21:20.085+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 22
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:21:20.095+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:21:20.159+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.108 seconds
[2025-01-22T23:21:30.681+0000] {processor.py:161} INFO - Started process (PID=19155) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:21:30.683+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:21:30.686+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:21:30.685+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:21:30.690+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:21:30.689+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 22
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:21:30.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:21:30.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.076 seconds
[2025-01-22T23:22:01.080+0000] {processor.py:161} INFO - Started process (PID=19222) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:22:01.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:22:01.084+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:22:01.084+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:22:01.088+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:22:01.087+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 22
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:22:01.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:22:01.118+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.042 seconds
[2025-01-22T23:22:11.073+0000] {processor.py:161} INFO - Started process (PID=19244) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:22:11.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:22:11.086+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:22:11.086+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:22:11.090+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:22:11.089+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 18
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:22:11.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:22:11.147+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.084 seconds
[2025-01-22T23:22:42.120+0000] {processor.py:161} INFO - Started process (PID=19310) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:22:42.122+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:22:42.134+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:22:42.133+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:22:42.138+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:22:42.137+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 18
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:22:42.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:22:42.181+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.066 seconds
[2025-01-22T23:23:05.571+0000] {processor.py:161} INFO - Started process (PID=19356) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:23:05.573+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:23:05.575+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:23:05.575+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:23:05.579+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:23:05.578+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 18
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:23:05.580+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:23:05.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.046 seconds
[2025-01-22T23:23:25.973+0000] {processor.py:161} INFO - Started process (PID=19403) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:23:25.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:23:25.976+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:23:25.975+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:23:25.979+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:23:25.978+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 18
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:23:25.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:23:26.006+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.038 seconds
[2025-01-22T23:23:56.350+0000] {processor.py:161} INFO - Started process (PID=19467) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:23:56.353+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:23:56.364+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:23:56.355+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:23:56.368+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:23:56.367+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task1_retrieve_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task1_retrieve_data.py", line 18
    def retrieve_data()
                      ^
SyntaxError: invalid syntax
[2025-01-22T23:23:56.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:23:56.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.085 seconds
[2025-01-22T23:24:04.900+0000] {processor.py:161} INFO - Started process (PID=19481) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:24:04.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:24:04.903+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:24:04.903+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:24:04.925+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:24:04.924+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:24:04.939+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:24:05.213+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:24:05.211+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:retrieve_data_from_web
[2025-01-22T23:24:05.278+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:24:05.277+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:retrieve_data_from_web
[2025-01-22T23:24:05.322+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:24:05.321+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:retrieve_data_from_web
[2025-01-22T23:24:05.322+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:24:05.322+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:24:05.373+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:24:05.372+0000] {dag.py:3058} INFO - Creating ORM DAG for retrieve_data_from_web
[2025-01-22T23:24:05.415+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:24:05.414+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to 2025-01-22 17:58:00+00:00, run_after=2025-01-22 17:59:00+00:00
[2025-01-22T23:24:05.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.559 seconds
[2025-01-22T23:24:35.661+0000] {processor.py:161} INFO - Started process (PID=19547) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:24:35.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:24:35.670+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:24:35.668+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:24:35.709+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:24:35.708+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:24:35.724+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:24:35.743+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:24:35.742+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:24:35.796+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:24:35.795+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to 2025-01-22 17:58:00+00:00, run_after=2025-01-22 17:59:00+00:00
[2025-01-22T23:24:35.863+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.208 seconds
[2025-01-22T23:24:39.974+0000] {processor.py:161} INFO - Started process (PID=19559) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:24:39.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:24:39.978+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:24:39.977+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:24:39.999+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:24:39.999+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:24:40.009+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:24:40.193+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:24:40.192+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:24:40.215+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:24:40.214+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:24:40.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.283 seconds
[2025-01-22T23:25:10.321+0000] {processor.py:161} INFO - Started process (PID=19625) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:25:10.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:25:10.327+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:25:10.326+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:25:10.365+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:25:10.365+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:25:10.376+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:25:10.394+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:25:10.393+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:25:10.417+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:25:10.417+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:25:10.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.134 seconds
[2025-01-22T23:25:40.560+0000] {processor.py:161} INFO - Started process (PID=19689) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:25:40.561+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:25:40.563+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:25:40.563+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:25:40.594+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:25:40.594+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:25:40.605+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:25:40.643+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:25:40.642+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:25:40.670+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:25:40.669+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:25:40.711+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.164 seconds
[2025-01-22T23:26:11.595+0000] {processor.py:161} INFO - Started process (PID=19757) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:26:11.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:26:11.615+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:26:11.614+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:26:11.645+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:26:11.644+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:26:11.663+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:26:11.690+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:26:11.689+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:26:11.715+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:26:11.714+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:26:11.765+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.175 seconds
[2025-01-22T23:26:20.140+0000] {processor.py:161} INFO - Started process (PID=19773) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:26:20.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:26:20.144+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:26:20.143+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:26:20.173+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:26:20.172+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:26:20.182+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:26:20.198+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:26:20.198+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:26:20.216+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:26:20.216+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:26:20.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.113 seconds
[2025-01-22T23:26:50.844+0000] {processor.py:161} INFO - Started process (PID=19839) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:26:50.846+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:26:50.849+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:26:50.848+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:26:50.868+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:26:50.868+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:26:50.879+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:26:50.898+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:26:50.897+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:26:50.948+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:26:50.948+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:26:51.026+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.187 seconds
[2025-01-22T23:27:21.271+0000] {processor.py:161} INFO - Started process (PID=19906) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:27:21.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:27:21.276+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:27:21.275+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:27:21.296+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:27:21.296+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:27:21.307+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:27:21.349+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:27:21.348+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:27:21.407+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:27:21.406+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:27:21.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.172 seconds
[2025-01-22T23:27:51.814+0000] {processor.py:161} INFO - Started process (PID=19972) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:27:51.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:27:51.827+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:27:51.827+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:27:51.874+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:27:51.874+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:27:51.885+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:27:51.918+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:27:51.917+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:27:51.941+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:27:51.941+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:27:51.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.174 seconds
[2025-01-22T23:28:22.283+0000] {processor.py:161} INFO - Started process (PID=20034) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:28:22.285+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:28:22.287+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:28:22.287+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:28:22.338+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:28:22.338+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:28:22.354+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:28:22.391+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:28:22.391+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:28:22.427+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:28:22.426+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:28:22.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.236 seconds
[2025-01-22T23:28:23.000+0000] {processor.py:161} INFO - Started process (PID=20039) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:28:23.001+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:28:23.003+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:28:23.003+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:28:23.059+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:28:23.059+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:28:23.077+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:28:23.113+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:28:23.113+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:28:23.154+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:28:23.154+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:28:23.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.250 seconds
[2025-01-22T23:28:53.538+0000] {processor.py:161} INFO - Started process (PID=20105) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:28:53.548+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:28:53.550+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:28:53.550+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:28:53.626+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:28:53.625+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:28:53.653+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:28:53.704+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:28:53.704+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:28:53.742+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:28:53.742+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:28:53.799+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.266 seconds
[2025-01-22T23:29:24.069+0000] {processor.py:161} INFO - Started process (PID=20169) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:29:24.070+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:29:24.072+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:29:24.071+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:29:24.094+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:29:24.093+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:29:24.104+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:29:24.123+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:29:24.123+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:29:24.148+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:29:24.147+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:29:24.180+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.118 seconds
[2025-01-22T23:29:33.189+0000] {processor.py:161} INFO - Started process (PID=20200) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:29:33.191+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:29:33.194+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:29:33.193+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:29:33.212+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:29:33.211+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:29:33.220+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:29:33.234+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:29:33.234+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:29:33.254+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:29:33.253+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:29:33.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.123 seconds
[2025-01-22T23:29:55.474+0000] {processor.py:161} INFO - Started process (PID=20245) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:29:55.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:29:55.477+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:29:55.477+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:29:55.523+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:29:55.523+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:29:55.539+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:29:55.581+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:29:55.580+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:29:55.655+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:29:55.655+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:29:55.714+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.245 seconds
[2025-01-22T23:30:05.910+0000] {processor.py:161} INFO - Started process (PID=20266) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:30:05.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:30:05.922+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:30:05.922+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:30:05.962+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:30:05.960+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:30:05.982+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:30:05.999+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:30:05.999+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:30:06.025+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:30:06.025+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:30:06.061+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.156 seconds
[2025-01-22T23:30:10.702+0000] {processor.py:161} INFO - Started process (PID=20278) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:30:10.703+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:30:10.707+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:30:10.706+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:30:10.747+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:30:10.747+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:30:10.780+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:30:10.815+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:30:10.815+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:30:10.838+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:30:10.837+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:30:10.902+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.212 seconds
[2025-01-22T23:30:19.597+0000] {processor.py:161} INFO - Started process (PID=20296) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:30:19.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:30:19.604+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:30:19.603+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:30:19.644+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:30:19.644+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:30:19.662+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:30:19.683+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:30:19.683+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:30:19.719+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:30:19.719+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:30:19.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.155 seconds
[2025-01-22T23:30:50.550+0000] {processor.py:161} INFO - Started process (PID=20361) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:30:50.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:30:50.556+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:30:50.555+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:30:50.581+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:30:50.580+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:30:50.616+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:30:50.634+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:30:50.634+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:30:50.655+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:30:50.655+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:30:50.682+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.137 seconds
[2025-01-22T23:31:20.781+0000] {processor.py:161} INFO - Started process (PID=20427) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:31:20.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:31:20.785+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:31:20.784+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:31:20.816+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:31:20.816+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:31:20.827+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:31:20.844+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:31:20.844+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:31:20.875+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:31:20.875+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:31:20.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.138 seconds
[2025-01-22T23:31:51.353+0000] {processor.py:161} INFO - Started process (PID=20493) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:31:51.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:31:51.363+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:31:51.363+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:31:51.394+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:31:51.393+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:31:51.406+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:31:51.423+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:31:51.423+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:31:51.446+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:31:51.446+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:31:51.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.147 seconds
[2025-01-22T23:32:21.592+0000] {processor.py:161} INFO - Started process (PID=20559) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:32:21.593+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:32:21.608+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:32:21.607+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:32:21.639+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:32:21.638+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:32:21.657+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:32:21.700+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:32:21.699+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:32:21.729+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:32:21.729+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:32:21.787+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.201 seconds
[2025-01-22T23:32:52.154+0000] {processor.py:161} INFO - Started process (PID=20624) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:32:52.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:32:52.171+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:32:52.171+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:32:52.210+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:32:52.210+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:32:52.228+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:32:52.268+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:32:52.268+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:32:52.310+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:32:52.310+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:32:52.367+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.227 seconds
[2025-01-22T23:33:22.568+0000] {processor.py:161} INFO - Started process (PID=20687) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:33:22.570+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:33:22.581+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:33:22.580+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:33:22.614+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:33:22.614+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:33:22.630+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:33:22.652+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:33:22.652+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:33:22.677+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:33:22.676+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:33:22.750+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.195 seconds
[2025-01-22T23:33:53.572+0000] {processor.py:161} INFO - Started process (PID=20752) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:33:53.575+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:33:53.597+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:33:53.596+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:33:53.710+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:33:53.709+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:33:53.745+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:33:53.819+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:33:53.818+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:33:53.875+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:33:53.874+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:33:53.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.438 seconds
[2025-01-22T23:34:24.921+0000] {processor.py:161} INFO - Started process (PID=20818) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:34:24.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:34:24.925+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:34:24.925+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:34:24.982+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:34:24.982+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:34:24.996+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:34:25.050+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:34:25.050+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:34:25.127+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:34:25.127+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:34:25.240+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.332 seconds
[2025-01-22T23:34:55.396+0000] {processor.py:161} INFO - Started process (PID=20875) to work on /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:34:55.403+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task1_retrieve_data.py for tasks to queue
[2025-01-22T23:34:55.406+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:34:55.405+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:34:55.424+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:34:55.423+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-22T23:34:55.442+0000] {processor.py:840} INFO - DAG(s) 'retrieve_data_from_web' retrieved from /opt/airflow/dags/task1_retrieve_data.py
[2025-01-22T23:34:55.475+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:34:55.475+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-01-22T23:34:55.528+0000] {logging_mixin.py:188} INFO - [2025-01-22T23:34:55.527+0000] {dag.py:3823} INFO - Setting next_dagrun for retrieve_data_from_web to None, run_after=None
[2025-01-22T23:34:55.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task1_retrieve_data.py took 0.219 seconds
